Repository Sparrowworks/Vanguard, pull requests merged in 2024-12, with the labels that each got.

#24 Shoot and Reload documentation + some renaming
  blueprints/armature/armature.gd
  blueprints/field/field.gd
  blueprints/projectile/projectile.gd
  blueprints/projectile/projectile.tscn
  weapons/pistol/pistol.gd
  weapons/pistol/pistol_bullet.gd
Labels: documentation

#29 fixes
  blueprints/armature/armature.gd
  blueprints/field/field.gd
  blueprints/projectile/projectile.gd
  blueprints/projectile/projectile.tscn
  test_scene/test.tscn
  weapons/pistol/pistol.gd
  weapons/pistol/pistol.tscn
  weapons/pistol/pistol_bullet.tscn
  weapons/pistol/pistol_noise.tscn
Labels: bug, enhancement

#35 Few documentation changes
  blueprints/armature/armature.gd
  blueprints/field/field.gd
  blueprints/projectile/projectile.gd
  weapons/pistol/pistol_bullet.tscn
Labels: documentation

#45 Kit fixes and debug
  blueprints/kit/ranged_stat_kit.gd
  blueprints/projectile/projectile.gd
  blueprints/ranged/ranged.gd
  test_scene/test.tscn
  weapons/pistol/base_pistol_stats.tres
  weapons/pistol/fast_bullet_update.tres
  weapons/pistol/fast_pistol_bullet.tscn
  weapons/pistol/pistol.gd
  weapons/pistol/pistol.tscn
  weapons/pistol/pistol_extended_mag.tres
  weapons/pistol/silent_pistol_noise.tscn
Labels: bug

#44 Gun attachment system
  blueprints/armature/armature.gd
  blueprints/armature/armature.tscn
  blueprints/kit/field_kit.gd
  blueprints/kit/field_kit.tres
  blueprints/kit/gun_kit.gd
  blueprints/kit/gun_kit.tres
  blueprints/kit/projectile_kit.gd
  blueprints/kit/projectile_kit.tres
  blueprints/kit/ranged_emission_kit.gd
  blueprints/kit/ranged_emission_kit.tres
  blueprints/kit/ranged_stat_kit.gd
  blueprints/kit/ranged_stat_kit.tres
  blueprints/projectile/projectile.gd
  blueprints/ranged/base_ranged_stats.tres
  blueprints/ranged/ranged.gd
  blueprints/ranged/ranged.tscn
  test_scene/test.tscn
  weapons/pistol/base_pistol_stats.tres
  weapons/pistol/emissions/fast_pistol_bullet.tscn
  weapons/pistol/emissions/pistol_bullet.gd
  weapons/pistol/emissions/pistol_bullet.tscn
  weapons/pistol/emissions/pistol_noise.tscn
  weapons/pistol/emissions/silent_pistol_noise.tscn
  weapons/pistol/kits/fast_bullet_update.tres
  weapons/pistol/kits/pistol_extended_mag.tres
  weapons/pistol/pistol.gd
  weapons/pistol/pistol.tscn
Labels: documentation, enhancement
